name: Parcel to MQTT
version: "0.1.0"
slug: parcel_to_mqtt
description: Publish parcel tracking data to Home Assistant via MQTT Discovery
url: https://github.com/rockbaer2007/parcel-to-mqtt
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
services:
  - mqtt:need
options:
  track17_api_key: ""
  tracking_numbers: ""
  interval: 60
  max_parcels: 6
  log_response_details: false
schema:
  track17_api_key: password
  tracking_numbers: str
  interval: int(30,1440)
  max_parcels: int(1,20)
  log_response_details: bool
