name: Parcel to MQTT
version: "0.1.4"
slug: parcel_to_mqtt
description: Publish parcel tracking data to Home Assistant via MQTT Discovery
url: https://github.com/rockbaer2007/parcel-to-mqtt
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
services:
  - mqtt:need
options:
  dhl_tracking_numbers: ""
  dhl_login_code: ""
  hermes_tracking_numbers: ""
  gls_tracking_numbers: ""
  gls_postal_code: ""
  interval: 60
  max_parcels: 6
  log_response_details: false
schema:
  dhl_tracking_numbers: str
  dhl_login_code: password
  hermes_tracking_numbers: str
  gls_tracking_numbers: str
  gls_postal_code: str
  interval: int(30,1440)
  max_parcels: int(1,20)
  log_response_details: bool
